before_install:
  - sudo apt-get install -y libgtk-3-dev python3-pytest
addons:
  apt:
    update: true

language: julia

julia:
  - 0.7
  - 1.0

os:
  - linux

script:
  - julia -q deps_install.jl 
  - julia -e 'include("runtests.jl")'
  - python3 generate_tests.py
  - py.test tests.py

