before_install:
  - sudo apt-get install -y libgtk-3-dev
addons:
  apt:
    update: true

language: julia

julia:
  - 1.0

os:
  - osx

script:
  - julia -q deps_install.jl 
  - julia -e 'include("runtests.jl")'
